In [1]:
import pandas as pd
from io import StringIO
import sys

# https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
df = pd.read_csv('adult.data', header=None)

In [2]:
df

0                  1       2              3   4   \
0      39          State-gov   77516      Bachelors  13   
1      50   Self-emp-not-inc   83311      Bachelors  13   
2      38            Private  215646        HS-grad   9   
3      53            Private  234721           11th   7   
4      28            Private  338409      Bachelors  13   
5      37            Private  284582        Masters  14   
6      49            Private  160187            9th   5   
7      52   Self-emp-not-inc  209642        HS-grad   9   
8      31            Private   45781        Masters  14   
9      42            Private  159449      Bachelors  13   
10     37            Private  280464   Some-college  10   
11     30          State-gov  141297      Bachelors  13   
12     23            Private  122272      Bachelors  13   
13     32            Private  205019     Assoc-acdm  12   
14     40            Private  121772      Assoc-voc  11   
15     34            Private  245487        7th-8th   4   
16     25   Self-emp-not-inc  176756        HS-grad   9   
17     32            Private  186824        HS-grad   9   
18     38            Private   28887           11th   7   
19     43   Self-emp-not-inc  292175        Masters  14   
20     40            Private  193524      Doctorate  16   
21     54            Private  302146        HS-grad   9   
22     35        Federal-gov   76845            9th   5   
23     43            Private  117037           11th   7   
24     59            Private  109015        HS-grad   9   
25     56          Local-gov  216851      Bachelors  13   
26     19            Private  168294        HS-grad   9   
27     54                  ?  180211   Some-college  10   
28     39            Private  367260        HS-grad   9   
29     49            Private  193366        HS-grad   9   
...    ..                ...     ...            ...  ..   
32531  30                  ?   33811      Bachelors  13   
32532  34            Private  204461      Doctorate  16   
32533  54            Private  337992      Bachelors  13   
32534  37            Private  179137   Some-college  10   
32535  22            Private  325033           12th   8   
32536  34            Private  160216      Bachelors  13   
32537  30            Private  345898        HS-grad   9   
32538  38            Private  139180      Bachelors  13   
32539  71                  ?  287372      Doctorate  16   
32540  45          State-gov  252208        HS-grad   9   
32541  41                  ?  202822        HS-grad   9   
32542  72                  ?  129912        HS-grad   9   
32543  45          Local-gov  119199     Assoc-acdm  12   
32544  31            Private  199655        Masters  14   
32545  39          Local-gov  111499     Assoc-acdm  12   
32546  37            Private  198216     Assoc-acdm  12   
32547  43            Private  260761        HS-grad   9   
32548  65   Self-emp-not-inc   99359    Prof-school  15   
32549  43          State-gov  255835   Some-college  10   
32550  43   Self-emp-not-inc   27242   Some-college  10   
32551  32            Private   34066           10th   6   
32552  43            Private   84661      Assoc-voc  11   
32553  32            Private  116138        Masters  14   
32554  53            Private  321865        Masters  14   
32555  22            Private  310152   Some-college  10   
32556  27            Private  257302     Assoc-acdm  12   
32557  40            Private  154374        HS-grad   9   
32558  58            Private  151910        HS-grad   9   
32559  22            Private  201490        HS-grad   9   
32560  52       Self-emp-inc  287927        HS-grad   9   

                           5                   6                7   \
0               Never-married        Adm-clerical    Not-in-family   
1          Married-civ-spouse     Exec-managerial          Husband   
2                    Divorced   Handlers-cleaners    Not-in-family   
3          Married-civ-spouse   Handlers-cleaners          Husband  

In [3]:
df.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship',
              'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'class-label']

In [4]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country class-label  
0          2174             0              40   United-States       <=50K  
1             0             0              13   United-States       <=50K  
2             0             0              40   United-States       <=50K  
3             0             0              40   United-States       <=50K  
4             0             0              40            Cuba       <=50K

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
class-label       32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [6]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
class-label       0
dtype: int64

In [7]:
import numpy as np

In [8]:
np.unique(df['class-label'])

array([' <=50K', ' >50K'], dtype=object)

In [9]:
class_label_mapping = {' <=50K': -1, ' >50K': 1}

In [10]:
df['class-label'] = df['class-label'].map(class_label_mapping)

In [11]:
df['class-label'].values

array([-1, -1, -1, ..., -1, -1,  1], dtype=int64)

In [12]:
y = df['class-label'].values
df.drop('class-label', axis=1, inplace=True,)

In [13]:
df.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [14]:
df['capital-gain'].value_counts()

0        29849
15024      347
7688       284
7298       246
99999      159
5178        97
3103        97
4386        70
5013        69
8614        55
3325        53
2174        48
10520       43
4064        42
4650        41
14084       41
20051       37
3137        37
27828       34
594         34
3908        32
2829        31
13550       27
6849        27
14344       26
1055        25
2885        24
3411        24
4787        23
2176        23
         ...  
9562         4
1086         4
25124        4
1424         3
2961         3
7896         3
4687         3
2936         3
1173         3
5721         3
2009         3
6360         3
41310        2
6723         2
3456         2
2993         2
401          2
11678        2
2062         2
18481        2
7978         1
1639         1
2538         1
2387         1
5060         1
4931         1
1455         1
6097         1
22040        1
1111         1
Name: capital-gain, Length: 119, dtype: int64

In [15]:
df['capital-loss'].value_counts()

0       31042
1902      202
1977      168
1887      159
1848       51
1485       51
2415       49
1602       47
1740       42
1590       40
1876       39
1672       34
1564       25
2258       25
1669       24
1741       24
2001       24
1980       23
1719       22
2002       21
2051       21
1408       21
1579       20
2377       20
1721       18
1504       18
1974       18
2339       17
2179       15
1628       15
        ...  
323         3
4356        3
2267        3
3683        2
1755        2
2352        2
1648        2
1138        2
810         2
1735        2
2238        2
2754        2
3004        2
3900        2
974         2
2149        2
1816        2
3770        2
2080        1
2489        1
2282        1
2163        1
155         1
2467        1
1844        1
1411        1
1539        1
2472        1
1944        1
2201        1
Name: capital-loss, Length: 92, dtype: int64

In [16]:
df['age'] = df['age'].astype(float)
df['fnlwgt'] = df['fnlwgt'].astype(float)
df['education-num'] = df['education-num'].astype(float)
df['hours-per-week'] = df['hours-per-week'].astype(float)

In [17]:
df.tail()

age      workclass    fnlwgt    education  education-num  \
32556  27.0        Private  257302.0   Assoc-acdm           12.0   
32557  40.0        Private  154374.0      HS-grad            9.0   
32558  58.0        Private  151910.0      HS-grad            9.0   
32559  22.0        Private  201490.0      HS-grad            9.0   
32560  52.0   Self-emp-inc  287927.0      HS-grad            9.0   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loss  hours-per-week  native-country  
32556             0             0            38.0   United-States  
32557             0             0            40.0   United-States  
32558             0             0            40.0   United-States  
32559             0             0            20.0   United-States  
32560         15024             0            40.0   United-States

In [18]:
df['workclass'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [19]:
df['education'].unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [20]:
df['marital-status'].unique()

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [21]:
df['occupation'].unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', ' ?', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [22]:
df['relationship'].unique()

array([' Not-in-family', ' Husband', ' Wife', ' Own-child', ' Unmarried',
       ' Other-relative'], dtype=object)

In [23]:
df['race'].unique()

array([' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo',
       ' Other'], dtype=object)

In [24]:
df['sex'].unique()

array([' Male', ' Female'], dtype=object)

In [25]:
df['native-country'].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

In [26]:
df = df.replace(' ?', 'NaN')

In [27]:
df.head()

age          workclass    fnlwgt   education  education-num  \
0  39.0          State-gov   77516.0   Bachelors           13.0   
1  50.0   Self-emp-not-inc   83311.0   Bachelors           13.0   
2  38.0            Private  215646.0     HS-grad            9.0   
3  53.0            Private  234721.0        11th            7.0   
4  28.0            Private  338409.0   Bachelors           13.0   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  
0          2174             0            40.0   United-States  
1             0             0            13.0   United-States  
2             0             0            40.0   United-States  
3             0             0            40.0   United-States  
4             0             0            40.0            Cuba

In [28]:
df = pd.get_dummies(df, columns=[
    'workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race',
    'sex', 'native-country',
])

In [29]:
df.shape

(32561, 108)

In [30]:
df

age    fnlwgt  education-num  capital-gain  capital-loss  \
0      39.0   77516.0           13.0          2174             0   
1      50.0   83311.0           13.0             0             0   
2      38.0  215646.0            9.0             0             0   
3      53.0  234721.0            7.0             0             0   
4      28.0  338409.0           13.0             0             0   
5      37.0  284582.0           14.0             0             0   
6      49.0  160187.0            5.0             0             0   
7      52.0  209642.0            9.0             0             0   
8      31.0   45781.0           14.0         14084             0   
9      42.0  159449.0           13.0          5178             0   
10     37.0  280464.0           10.0             0             0   
11     30.0  141297.0           13.0             0             0   
12     23.0  122272.0           13.0             0             0   
13     32.0  205019.0           12.0             0             0   
14     40.0  121772.0           11.0             0             0   
15     34.0  245487.0            4.0             0             0   
16     25.0  176756.0            9.0             0             0   
17     32.0  186824.0            9.0             0             0   
18     38.0   28887.0            7.0             0             0   
19     43.0  292175.0           14.0             0             0   
20     40.0  193524.0           16.0             0             0   
21     54.0  302146.0            9.0             0             0   
22     35.0   76845.0            5.0             0             0   
23     43.0  117037.0            7.0             0          2042   
24     59.0  109015.0            9.0             0             0   
25     56.0  216851.0           13.0             0             0   
26     19.0  168294.0            9.0             0             0   
27     54.0  180211.0           10.0             0             0   
28     39.0  367260.0            9.0             0             0   
29     49.0  193366.0            9.0             0             0   
...     ...       ...            ...           ...           ...   
32531  30.0   33811.0           13.0             0             0   
32532  34.0  204461.0           16.0             0             0   
32533  54.0  337992.0           13.0             0             0   
32534  37.0  179137.0           10.0             0             0   
32535  22.0  325033.0            8.0             0             0   
32536  34.0  160216.0           13.0             0             0   
32537  30.0  345898.0            9.0             0             0   
32538  38.0  139180.0           13.0         15020             0   
32539  71.0  287372.0           16.0             0             0   
32540  45.0  252208.0            9.0             0             0   
32541  41.0  202822.0            9.0             0             0   
32542  72.0  129912.0            9.0             0             0   
32543  45.0  119199.0           12.0             0             0   
32544  31.0  199655.0           14.0             0             0   
32545  39.0  111499.0           12.0             0             0   
32546  37.0  198216.0           12.0             0             0   
32547  43.0  260761.0            9.0             0             0   
32548  65.0   99359.0           15.0          1086             0   
32549  43.0  255835.0           10.0             0             0   
32550  43.0   27242.0           10.0             0             0   
32551  32.0   34066.0            6.0             0             0   
32552  43.0   84661.0           11.0             0             0   
32553  32.0  116138.0           14.0             0             0   
32554  53.0  321865.0           14.0             0             0   
32555  22.0  310152.0           10.0             0             0   
32556  27.0  257302.0           12.0             0             0   
32557  40.0  154374.0            9.0             0             0

In [31]:
from sklearn.preprocessing import Imputer
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
X = imputed_data

C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [32]:
pd.value_counts(pd.Series(y))

-1    24720
 1     7841
dtype: int64

In [33]:
X

array([[3.90000e+01, 7.75160e+04, 1.30000e+01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [5.00000e+01, 8.33110e+04, 1.30000e+01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [3.80000e+01, 2.15646e+05, 9.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [5.80000e+01, 1.51910e+05, 9.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.20000e+01, 2.01490e+05, 9.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [5.20000e+01, 2.87927e+05, 9.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=0)

In [36]:
from libs import transform

In [37]:
import importlib

In [38]:
importlib.reload(transform)

<module 'libs.transform' from 'C:\\Users\\Lucas\\Documents\\python-machine-learning\\Cross Validation Adult Dataset\\libs\\transform.py'>

In [39]:
std = transform.Standardize()

In [40]:
std.fit(X_train)

In [41]:
X_train_std = std.transform(X_train)
X_test_std = std.transform(X_test)

# 5-Fold Cross Validation

In [42]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [43]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5)
skf.get_n_splits(X_train_std, y_train)

print(skf)

for train_index, test_index in skf.split(X_train_std, y_train):
   print("TRAIN:", train_index, "TEST:", test_index)
   k_X_train, k_X_test = X_train_std[train_index], X_train_std[test_index]
   k_y_train, k_y_test = y_train[train_index], y_train[test_index]

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)
TRAIN: [ 4519  4522  4523 ... 22789 22790 22791] TEST: [   0    1    2 ... 4566 4567 4568]
TRAIN: [    0     1     2 ... 22789 22790 22791] TEST: [4519 4522 4523 ... 9124 9128 9129]
TRAIN: [    0     1     2 ... 22789 22790 22791] TEST: [ 9085  9087  9088 ... 13838 13846 13853]
TRAIN: [    0     1     2 ... 22789 22790 22791] TEST: [13632 13634 13635 ... 18279 18282 18287]
TRAIN: [    0     1     2 ... 18279 18282 18287] TEST: [18222 18224 18225 ... 22789 22790 22791]


In [44]:
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm

# Perceptron

In [45]:
perceptron = Perceptron()

In [46]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(perceptron, k_X_train, k_y_train, cv=5))

[0.78755482 0.7908443  0.77104469 0.78606692 0.77729018]


# SGD

In [47]:
sgd = SGDClassifier()

In [48]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(sgd, k_X_train, k_y_train, cv=5))

[0.79166667 0.24095395 0.79489992 0.77921009 0.77290181]


# Logistic Regression

In [49]:
lr = LogisticRegression()

In [50]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(lr, k_X_train, k_y_train, cv=5))

[0.796875   0.79989035 0.79846449 0.80087767 0.79786067]


# kNN

In [51]:
knn = KNeighborsClassifier()

In [52]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(knn, k_X_train, k_y_train, cv=5))

[0.77138158 0.77796053 0.76638333 0.7668678  0.77290181]


# Naive Bayes

In [53]:
naive_bayes = GaussianNB()

In [54]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(naive_bayes, k_X_train, k_y_train, cv=5))

[0.78919956 0.79769737 0.78886756 0.79566648 0.79155239]


# SVM

In [55]:
svm = svm.SVC(gamma='scale')

In [56]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(svm, k_X_train, k_y_train, cv=5))

[0.78700658 0.78782895 0.78639978 0.78743829 0.78277564]


# Decision Tree

In [57]:
tree = DecisionTreeClassifier(random_state=0)

In [58]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(tree, k_X_train, k_y_train, cv=5))

[0.81003289 0.80674342 0.80888401 0.81212287 0.81075151]
