In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('wdbc.data', header=None)

In [3]:
df.head()

0  1      2      3       4       5        6        7       8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        9   ...     22     23      24      25      26      27      28      29  \
0  0.14710  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       30       31  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 32 columns]

In [4]:
df.columns = ['id','diagnosis','1','2','3','4','5','6','7','8','9','10',
                               '11','12','13','14','15','16','17','18','19','20',
                               '21','22','23','24','25','26','27','28','29','30'
             ]

In [5]:
df.tail()

id diagnosis      1      2       3       4        5        6  \
564  926424         M  21.56  22.39  142.00  1479.0  0.11100  0.11590   
565  926682         M  20.13  28.25  131.20  1261.0  0.09780  0.10340   
566  926954         M  16.60  28.08  108.30   858.1  0.08455  0.10230   
567  927241         M  20.60  29.33  140.10  1265.0  0.11780  0.27700   
568   92751         B   7.76  24.54   47.92   181.0  0.05263  0.04362   

           7        8  ...      21     22      23      24       25       26  \
564  0.24390  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130   
565  0.14400  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220   
566  0.09251  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940   
567  0.35140  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810   
568  0.00000  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444   

         27      28      29       30  
564  0.4107  0.2216  0.2060  0.07115  
565  0.3215  0.1628  0.2572  0.06637  
566  0.3403  0.1418  0.2218  0.07820  
567  0.9387  0.2650  0.4087  0.12400  
568  0.0000  0.0000  0.2871  0.07039  

[5 rows x 32 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
id           569 non-null int64
diagnosis    569 non-null object
1            569 non-null float64
2            569 non-null float64
3            569 non-null float64
4            569 non-null float64
5            569 non-null float64
6            569 non-null float64
7            569 non-null float64
8            569 non-null float64
9            569 non-null float64
10           569 non-null float64
11           569 non-null float64
12           569 non-null float64
13           569 non-null float64
14           569 non-null float64
15           569 non-null float64
16           569 non-null float64
17           569 non-null float64
18           569 non-null float64
19           569 non-null float64
20           569 non-null float64
21           569 non-null float64
22           569 non-null float64
23           569 non-null float64
24           569 non-null float64
25           5

In [7]:
df.isna().sum()

id           0
diagnosis    0
1            0
2            0
3            0
4            0
5            0
6            0
7            0
8            0
9            0
10           0
11           0
12           0
13           0
14           0
15           0
16           0
17           0
18           0
19           0
20           0
21           0
22           0
23           0
24           0
25           0
26           0
27           0
28           0
29           0
30           0
dtype: int64

In [8]:
df.describe()

id           1           2           3            4  \
count  5.690000e+02  569.000000  569.000000  569.000000   569.000000   
mean   3.037183e+07   14.127292   19.289649   91.969033   654.889104   
std    1.250206e+08    3.524049    4.301036   24.298981   351.914129   
min    8.670000e+03    6.981000    9.710000   43.790000   143.500000   
25%    8.692180e+05   11.700000   16.170000   75.170000   420.300000   
50%    9.060240e+05   13.370000   18.840000   86.240000   551.100000   
75%    8.813129e+06   15.780000   21.800000  104.100000   782.700000   
max    9.113205e+08   28.110000   39.280000  188.500000  2501.000000   

                5           6           7           8           9  ...  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  ...   
mean     0.096360    0.104341    0.088799    0.048919    0.181162  ...   
std      0.014064    0.052813    0.079720    0.038803    0.027414  ...   
min      0.052630    0.019380    0.000000    0.000000    0.106000  ...   
25%      0.086370    0.064920    0.029560    0.020310    0.161900  ...   
50%      0.095870    0.092630    0.061540    0.033500    0.179200  ...   
75%      0.105300    0.130400    0.130700    0.074000    0.195700  ...   
max      0.163400    0.345400    0.426800    0.201200    0.304000  ...   

               21          22          23           24          25  \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    16.269190   25.677223  107.261213   880.583128    0.132369   
std      4.833242    6.146258   33.602542   569.356993    0.022832   
min      7.930000   12.020000   50.410000   185.200000    0.071170   
25%     13.010000   21.080000   84.110000   515.300000    0.116600   
50%     14.970000   25.410000   97.660000   686.500000    0.131300   
75%     18.790000   29.720000  125.400000  1084.000000    0.146000   
max     36.040000   49.540000  251.200000  4254.000000    0.222600   

               26          27          28          29          30  
count  569.000000  569.000000  569.000000  569.000000  569.000000  
mean     0.254265    0.272188    0.114606    0.290076    0.083946  
std      0.157336    0.208624    0.065732    0.061867    0.018061  
min      0.027290    0.000000    0.000000    0.156500    0.055040  
25%      0.147200    0.114500    0.064930    0.250400    0.071460  
50%      0.211900    0.226700    0.099930    0.282200    0.080040  
75%      0.339100    0.382900    0.161400    0.317900    0.092080  
max      1.058000    1.252000    0.291000    0.663800    0.207500  

[8 rows x 31 columns]

In [9]:
import numpy as np

In [10]:
np.unique(df['diagnosis'])

array(['B', 'M'], dtype=object)

In [11]:
class_label_mapping = {'B' : 1, 'M' : -1}

In [12]:
df['diagnosis'] = df['diagnosis'].map(class_label_mapping)

In [13]:
df['diagnosis'].values

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1,  1,
        1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,
        1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
       -1, -1, -1,  1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
        1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1, -1,
        1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1,
        1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1,  1, -1,
        1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1, -1,
        1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1,  1,
        1,  1, -1,  1,  1

In [14]:
y = df['diagnosis'].values

In [15]:
df.drop('diagnosis', axis=1, inplace=True)
df.drop('id', axis=1, inplace=True)

In [16]:
df.head()

1      2       3       4        5        6       7        8       9  \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        10  ...     21     22      23      24      25      26      27      28  \
0  0.07871  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.05667  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.05999  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.09744  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.05883  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       29       30  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 30 columns]

In [17]:
df.describe()

1           2           3            4           5  \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    14.127292   19.289649   91.969033   654.889104    0.096360   
std      3.524049    4.301036   24.298981   351.914129    0.014064   
min      6.981000    9.710000   43.790000   143.500000    0.052630   
25%     11.700000   16.170000   75.170000   420.300000    0.086370   
50%     13.370000   18.840000   86.240000   551.100000    0.095870   
75%     15.780000   21.800000  104.100000   782.700000    0.105300   
max     28.110000   39.280000  188.500000  2501.000000    0.163400   

                6           7           8           9          10  ...  \
count  569.000000  569.000000  569.000000  569.000000  569.000000  ...   
mean     0.104341    0.088799    0.048919    0.181162    0.062798  ...   
std      0.052813    0.079720    0.038803    0.027414    0.007060  ...   
min      0.019380    0.000000    0.000000    0.106000    0.049960  ...   
25%      0.064920    0.029560    0.020310    0.161900    0.057700  ...   
50%      0.092630    0.061540    0.033500    0.179200    0.061540  ...   
75%      0.130400    0.130700    0.074000    0.195700    0.066120  ...   
max      0.345400    0.426800    0.201200    0.304000    0.097440  ...   

               21          22          23           24          25  \
count  569.000000  569.000000  569.000000   569.000000  569.000000   
mean    16.269190   25.677223  107.261213   880.583128    0.132369   
std      4.833242    6.146258   33.602542   569.356993    0.022832   
min      7.930000   12.020000   50.410000   185.200000    0.071170   
25%     13.010000   21.080000   84.110000   515.300000    0.116600   
50%     14.970000   25.410000   97.660000   686.500000    0.131300   
75%     18.790000   29.720000  125.400000  1084.000000    0.146000   
max     36.040000   49.540000  251.200000  4254.000000    0.222600   

               26          27          28          29          30  
count  569.000000  569.000000  569.000000  569.000000  569.000000  
mean     0.254265    0.272188    0.114606    0.290076    0.083946  
std      0.157336    0.208624    0.065732    0.061867    0.018061  
min      0.027290    0.000000    0.000000    0.156500    0.055040  
25%      0.147200    0.114500    0.064930    0.250400    0.071460  
50%      0.211900    0.226700    0.099930    0.282200    0.080040  
75%      0.339100    0.382900    0.161400    0.317900    0.092080  
max      1.058000    1.252000    0.291000    0.663800    0.207500  

[8 rows x 30 columns]

In [18]:
X = df.values

In [19]:
X.shape

(569, 30)

In [20]:
y.shape

(569,)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42, shuffle=True)

In [23]:
X_train.shape

(455, 30)

In [24]:
X_test.shape

(114, 30)

In [25]:
y_train.shape

(455,)

In [26]:
y_test.shape

(114,)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
std = StandardScaler()

In [29]:
X_train_std = std.fit_transform(X_train)
X_test_std = std.transform(X_test)

In [30]:
X_train_std[0:5]

array([[-1.07200079e+00, -6.58424598e-01, -1.08808010e+00,
        -9.39273639e-01, -1.35939882e-01, -1.00871795e+00,
        -9.68358632e-01, -1.10203235e+00,  2.81062120e-01,
        -1.13231479e-01, -7.04860874e-01, -4.40938351e-01,
        -7.43948977e-01, -6.29804931e-01,  7.48061001e-04,
        -9.91572979e-01, -6.93759567e-01, -9.83284458e-01,
        -5.91579010e-01, -4.28972052e-01, -1.03409427e+00,
        -6.23497432e-01, -1.07077336e+00, -8.76534437e-01,
        -1.69982346e-01, -1.03883630e+00, -1.07899452e+00,
        -1.35052668e+00, -3.52658049e-01, -5.41380026e-01],
       [ 1.74874285e+00,  6.65017334e-02,  1.75115682e+00,
         1.74555856e+00,  1.27446827e+00,  8.42288215e-01,
         1.51985232e+00,  1.99466430e+00, -2.93045055e-01,
        -3.20179716e-01,  1.27567198e-01, -3.81382677e-01,
         9.40746962e-02,  3.17524379e-01,  6.39656015e-01,
         8.73892616e-02,  7.08450758e-01,  1.18215034e+00,
         4.26212305e-01,  7.47970186e-02,  1.22834212e+

In [31]:
X_test_std[0:5]

array([[ 1.56851278e+00,  2.16401585e+00,  1.74286587e+00,
         1.62076364e+00, -2.65376073e-01,  1.91593165e+00,
         1.09245512e+00,  1.69889576e+00,  3.09589185e-01,
        -6.98842131e-02,  1.65823310e+00, -3.45584597e-02,
         2.19927944e+00,  1.60979470e+00, -2.32336800e-01,
         1.19871549e+00,  1.87956718e-01,  5.59816638e-01,
        -1.62073360e-01,  5.23832065e-01,  1.86216011e+00,
         1.70820774e+00,  2.17062246e+00,  1.91370109e+00,
        -1.87740065e-01,  1.74427462e+00,  6.88560036e-01,
         1.20214432e+00, -1.40430640e-01,  9.00361713e-01],
       [-8.40276411e-01, -5.97067197e-01, -8.74173505e-01,
        -7.76169575e-01, -1.09034582e+00, -1.22569119e+00,
        -9.24639205e-01, -8.91007924e-01, -1.05257815e+00,
        -1.87341321e-01, -9.62401486e-01, -4.40763187e-01,
        -9.40772939e-01, -7.08093836e-01, -3.83363018e-01,
        -1.04491664e+00, -7.16088545e-01, -8.72824204e-01,
        -7.86852945e-02, -5.11433179e-01, -9.43848666e-

In [32]:
from sklearn.linear_model import Perceptron

In [33]:
perceptron_none = Perceptron(penalty=None, alpha=0.0001)

In [34]:
perceptron_l1 = Perceptron(penalty='l1', alpha=0.001)

In [35]:
perceptron_l2 = Perceptron(penalty='l2', alpha=0.01)

In [36]:
perceptron_elasticnet = Perceptron(penalty='elasticnet', alpha=0.1)

In [37]:
perceptron_none.fit(X_train_std, y_train)
perceptron_l1.fit(X_train_std, y_train)
perceptron_l2.fit(X_train_std, y_train)
perceptron_elasticnet.fit(X_train_std, y_train)

C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol

Perceptron(alpha=0.1, class_weight=None, early_stopping=False, eta0=1.0,
      fit_intercept=True, max_iter=None, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty='elasticnet', random_state=0, shuffle=True,
      tol=None, validation_fraction=0.1, verbose=0, warm_start=False)

In [38]:
def accuracy(y_pred, y_test):
    return sum(y_pred == y_test) / y_test.shape[0]

In [39]:
y_pred = perceptron_none.predict(X_test_std)

In [40]:
print(accuracy(y_pred, y_test))

0.9736842105263158


In [41]:
y_pred = perceptron_l1.predict(X_test_std)

In [42]:
print(accuracy(y_pred, y_test))

0.9385964912280702


In [43]:
y_pred = perceptron_l2.predict(X_test_std)

In [44]:
print(accuracy(y_pred, y_test))

0.9649122807017544


In [45]:
y_pred = perceptron_elasticnet.predict(X_test_std)

In [46]:
print(accuracy(y_pred, y_test))

0.8859649122807017


In [47]:
from sklearn.model_selection import cross_val_score, StratifiedKFold

In [48]:
skf = StratifiedKFold(n_splits=3, random_state=42, shuffle=True)

In [49]:
'''
for train_index, test_index in skf.split(X, y):
    X_train_skf, X_test_skf = X[train_index], X[test_index]
    y_train_skf, y_test_skf = y[train_index], y[test_index]
'''

'\nfor train_index, test_index in skf.split(X, y):\n    X_train_skf, X_test_skf = X[train_index], X[test_index]\n    y_train_skf, y_test_skf = y[train_index], y[test_index]\n'

In [50]:
cvs_perceptron_none = cross_val_score(perceptron_none, X_test_std, y_test, cv=skf)

C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol

In [51]:
print(cvs_perceptron_none)

[0.94736842 0.94736842 0.92105263]


In [52]:
cvs_perceptron_l1 = cross_val_score(perceptron_l1, X_test_std, y_test, cv=skf)

C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol

In [53]:
print(cvs_perceptron_l1)

[0.94736842 0.94736842 0.89473684]


In [54]:
cvs_perceptron_l2 = cross_val_score(perceptron_l2, X_test_std, y_test, cv=skf)

C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol

In [55]:
print(cvs_perceptron_l2)

[0.92105263 0.94736842 0.89473684]


In [56]:
cvs_perceptron_elasticnet = cross_val_score(perceptron_elasticnet, X_test_std, y_test, cv=skf)

C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol

In [57]:
print(cvs_perceptron_elasticnet)

[0.81578947 0.86842105 0.71052632]


In [58]:
perceptron = Perceptron()

In [59]:
perceptron.fit(X_train_std, y_train)

C:\Users\Lucas\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
      fit_intercept=True, max_iter=None, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=None,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [60]:
y_pred = perceptron.predict(X_test_std)

In [61]:
print(accuracy(y_pred, y_test))

0.9736842105263158
